target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-8'    # Swift Concurrency implementation
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-8'  # Combine implementation
end